<?php

namespace App\Services;

use App\Models\AccountPlan;
use Illuminate\Support\Str;

class PlanService
{
    /**
     * Get or create account plan for a session
     */
    public function getOrCreatePlan(string $sessionId, ?string $companyName = null): AccountPlan
    {
        return AccountPlan::firstOrCreate(
            ['session_id' => $sessionId],
            [
                'company_name' => $companyName ?? '',
                'overview' => '',
                'products' => [],
                'competitors' => [],
                'opportunities' => [],
                'recommendations' => [],
                'market_position' => '',
                'financial_summary' => '',
                'key_contacts' => [],
            ]
        );
    }

    /**
     * Update a specific section of the plan with evidence
     */
    public function updateSection(string $sessionId, string $section, mixed $content, array $evidence = []): AccountPlan
    {
        $plan = $this->getOrCreatePlan($sessionId);

        // Handle array sections
        if (in_array($section, ['products', 'competitors', 'opportunities', 'recommendations', 'key_contacts'])) {
            if (is_array($content)) {
                $plan->$section = $content;
            } else {
                // If string provided, try to parse as JSON or create array
                $decoded = json_decode($content, true);
                $plan->$section = $decoded ?? [$content];
            }
        } else {
            // Handle string sections
            $plan->$section = is_string($content) ? $content : json_encode($content);
        }

        // Store evidence if provided (could add evidence field to model if needed)
        if (!empty($evidence)) {
            // For now, we'll store evidence in metadata or append to content
            // You can extend the AccountPlan model to have an evidence field if needed
        }

        $plan->save();

        return $plan;
    }

    /**
     * Update company name
     */
    public function updateCompanyName(string $sessionId, string $companyName): AccountPlan
    {
        $plan = $this->getOrCreatePlan($sessionId);
        $plan->company_name = $companyName;
        $plan->save();

        return $plan;
    }

    /**
     * Get plan by session ID
     */
    public function getPlan(string $sessionId): ?AccountPlan
    {
        return AccountPlan::where('session_id', $sessionId)->first();
    }

    /**
     * Get all sections of a plan
     */
    public function getPlanSections(string $sessionId): array
    {
        $plan = $this->getPlan($sessionId);

        if (!$plan) {
            return [];
        }

        return [
            'company_name' => $plan->company_name,
            'overview' => $plan->overview,
            'products' => $plan->products ?? [],
            'competitors' => $plan->competitors ?? [],
            'opportunities' => $plan->opportunities ?? [],
            'recommendations' => $plan->recommendations ?? [],
            'market_position' => $plan->market_position,
            'financial_summary' => $plan->financial_summary,
            'key_contacts' => $plan->key_contacts ?? [],
        ];
    }

    /**
     * Regenerate a specific section
     */
    public function regenerateSection(string $sessionId, string $section): AccountPlan
    {
        // Clear the section - will be regenerated by agent
        return $this->updateSection($sessionId, $section, '');
    }
}

